### ISSUE TITLE
cyhy-mailer unable to read AWS config

### ISSUE THREAD

**Issue by dav3r** [cisagov/cyhy_amis#264]
# 🐛 Bug Report

Recent commit https://github.com/cisagov/cyhy_amis/commit/39b15570782e99f8e1dbfc83e7dfff9f862ff816 made the file `/var/cyhy/cyhy-mailer/secrets/aws_config` unreadable by anyone except for the `cyhy` user and `cyhy` group.  This prevented the `cyhy-mailer` container on `docker.prod-a.bod` from being able to run successfully, due to this error: `botocore.exceptions.ProfileNotFound: The config profile (default) could not be found`

## To Reproduce

- `ssh docker.prod-a.bod`
- `cd /var/cyhy/cyhy-mailer`
- `docker-compose ps`
- `docker-compose logs --follow`

## Expected behavior

The `cyhy-mailer` process should have sent the BOD emails without failure.

## Any helpful log output

Here is the output seen via `docker-compose logs --follow`:

```bash
mailer_1  | Traceback (most recent call last):
mailer_1  |   File "/usr/local/bin/cyhy-mailer", line 8, in <module>
mailer_1  |     sys.exit(main())
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/cyhy/mailer/cli.py", line 1023, in main
mailer_1  |     ses_client = boto3.client("ses")
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/boto3/__init__.py", line 91, in client
mailer_1  |     return _get_default_session().client(*args, **kwargs)
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/boto3/__init__.py", line 80, in _get_default_session
mailer_1  |     setup_default_session()
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/boto3/__init__.py", line 34, in setup_default_session
mailer_1  |     DEFAULT_SESSION = Session(**kwargs)
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/boto3/session.py", line 80, in __init__
mailer_1  |     self._setup_loader()
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/boto3/session.py", line 120, in _setup_loader
mailer_1  |     self._loader = self._session.get_component('data_loader')
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/botocore/session.py", line 682, in get_component
mailer_1  |     return self._components.get_component(name)
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/botocore/session.py", line 919, in get_component
mailer_1  |     self._components[name] = factory()
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/botocore/session.py", line 155, in <lambda>
mailer_1  |     lambda:  create_loader(self.get_config_variable('data_path')))
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/botocore/session.py", line 237, in get_config_variable
mailer_1  |     return self.get_component('config_store').get_config_variable(
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/botocore/configprovider.py", line 293, in get_config_variable
mailer_1  |     return provider.provide()
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/botocore/configprovider.py", line 390, in provide
mailer_1  |     value = provider.provide()
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/botocore/configprovider.py", line 451, in provide
mailer_1  |     scoped_config = self._session.get_scoped_config()
mailer_1  |   File "/usr/local/lib/python3.8/site-packages/botocore/session.py", line 337, in get_scoped_config
mailer_1  |     raise ProfileNotFound(profile=profile_name)
mailer_1  | botocore.exceptions.ProfileNotFound: The config profile (default) could not be found
```

**Comment by dav3r** [comment]
Note that this morning (during the weekly reporting), this issue only affected BOD reports and not CyHy reports because we have not yet deployed the code with https://github.com/cisagov/cyhy_amis/commit/39b15570782e99f8e1dbfc83e7dfff9f862ff816 to `reporter.prod-a.cyhy`.
